GET http://localhost:8000/api/categories


###
PUT http://localhost:8000/api/categories/20/exclude/
Content-Type: application/json

{
  "exclude": false
}


###
POST http://localhost:8000/api/categories/create
Content-Type: application/json

{
  "name": "test different user",
  "iconName": "test",
  "iconColor": "test",
  "exclude": false
}

###
DELETE http://localhost:8000/api/categories/1/delete

###
PUT http://localhost:8000/api/categories/1/update
Content-Type: application/json

{
  "name": "testupd",
  "iconName": "test",
  "iconColor": "test",
  "exclude": false
}
