GET http://localhost:8000/api/categories

###
GET http://localhost:8000/api/categories/userdefined


###
PUT http://localhost:8000/api/categories/14/exclude/
Content-Type: application/json

{
  "exclude": false
}


###
POST http://localhost:8000/api/categories/create
Content-Type: application/json

{
  "name": "no icon",
  "iconName": "notthere",
  "iconColor": "primary",
  "exclude": false
}

###
DELETE http://localhost:8000/api/categories/22/delete

###
PUT http://localhost:8000/api/categories/19/update
Content-Type: application/json

{
  "name": "bills  ud",
  "iconName": "bills",
  "iconColor": "test",
  "exclude": false
}
