GET http://localhost:8000/api/plaid/transactions

###
GET http://localhost:8000/api/plaid/accounts

###
GET http://localhost:8000/api/plaid/identity

###
GET http://localhost:8000/api/plaid/item


###
GET http://localhost:8000/api/plaid/balance

###
GET http://localhost:8000/api/plaid/categories

###
POST http://localhost:8000/api/plaid/sync_transactions
Content-Type: application/json
 
{
  "plaidItemId": "vjK6o1oe6JFn6q1pPKp7uM6gDo5w4dCWXyRn6"
}


