GET http://localhost:8000/api/transactions

###
GET http://localhost:8000/api/transactions/id/3966

###
GET http://localhost:8000/api/transactions/spending?startDate=2021-09-01&endDate=2022-08-31


### Latest expenses
GET http://localhost:8000/api/transactions?endDate=2022-07-31&limit=3&orderBy=txDate&offset=1



###
GET http://localhost:8000/api/transactions/account/1/summary

###
GET http://localhost:8000/api/transactions/spending/compare/bycategory?refDate=2022-07-15

###
GET http://localhost:8000/api/transactions/transactions_summary?startDate=2022-05-01&endDate=2022-10-31


###
GET http://localhost:8000/api/transactions/spending/?startDate=2022-05-01&endDate=2022-10-31


###
GET http://localhost:8000/api/transactions/top_merchants?startDate=2022-07-01&endDate=2022-07-31

###
POST http://localhost:8000/api/transactions/exclude/
Content-Type: application/json

{
  "transactionId": 343,
  "exclude": true
}

###
POST http://localhost:8000/api/transactions/category/
Content-Type: application/json

{
  "transactionId": 2250,
  "categoryId":19
}


###
GET http://localhost:8000/api/transactions/find_similar?transactionId=3966


###
PUT http://localhost:8000/api/transactions/update_category_similar
Content-Type: application/json

{
  "transactionId": 2246,
  "categoryId":15
}


###
PUT http://localhost:8000/api/transactions/update_category
Content-Type: application/json

{
  "transactionId": 2246,
  "categoryId":15
}

###
GET http://localhost:8000/api/transactions/similar_count?transactionId=3966


###
GET http://localhost:8000/api/transactions/spending/compare/cumulative?refDate=2022-08-15


###
GET http://localhost:8000/api/transactions/spending/compare/bycategory?refDate=2022-05-15


### Get Last transactions
GET http://localhost:8000/api/transactions?endDate=2022-07-31&limit=10&orderBy=txDate&onlyPositiveAmounts=true

### Get monthly spend
GET http://localhost:8000/api/transactions/spending?startDate=2021-06-01&endDate=2022-05-31


### spending by category
GET http://localhost:8000/api/transactions/spending/bycategory?startDate=2022-07-01&endDate=2022-07-31&removeZeroCounts=true

### spending by account
GET http://localhost:8000/api/transactions/spending/byaccount?startDate=2022-07-01&endDate=2022-07-31&removeZeroCounts=true

###
 http://localhost:8000/api/transactions/spending?startDate=2019-11-01&endDate=2020-12-31

###
GET http://localhost:8000/api/transactions/dates