GET http://localhost:8000/api/transactions

###
GET http://localhost:8000/api/transactions/2256

###
GET http://localhost:8000/api/transactions?startDate=2022-07-01&endDate=2022-07-05&limit=5


###
GET http://localhost:8000/api/transactions/account/1/summary

###
GET http://localhost:8000/api/transactions/spending_summary_category?startDate=2022-05-01&endDate=2022-07-31

###
GET http://localhost:8000/api/transactions/transactions_summary?startDate=2022-05-01&endDate=2022-10-31

###
GET http://localhost:8000/api/transactions/top_merchants?startDate=2022-07-01&endDate=2022-07-31

###
POST http://localhost:8000/api/transactions/exclude/
Content-Type: application/json

{
  "transactionId": 343,
  "exclude": true
}

###
POST http://localhost:8000/api/transactions/category/
Content-Type: application/json

{
  "transactionId": 2250,
  "categoryId":19
}


###
GET http://localhost:8000/api/transactions/find_similar?transactionId=634


###
PUT http://localhost:8000/api/transactions/update_category_similar
Content-Type: application/json

{
  "transactionId": 2246,
  "categoryId":15
}


###
PUT http://localhost:8000/api/transactions/update_category
Content-Type: application/json

{
  "transactionId": 2246,
  "categoryId":15
}

###
GET http://localhost:8000/api/transactions/similar_count?transactionId=2246


###
GET http://localhost:8000/api/transactions/spending/byday?startDate=2022-05-01&endDate=2022-05-31

###
GET http://localhost:8000/api/transactions/spending/trend?refDate=2022-05-15
